language: node_js
node_js:
  - 10
before_script:
  - export NODE_OPTIONS=--max-old-space-size=4096
jobs: 
  include: 
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test
